spring:
  datasource:
    url: jdbc:mysql://msdocs-mysql-sample.mysql.database.azure.com:3306/demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: azure_mysql
    password: Huawei@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis相关配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      # 配置redis的主机地址，需要修改成自己的
      port: 63791
      password:
      timeout: 5000
      jedis:
        pool:
          # 连接池中的最大空闲连接，默认值也是8。
          max-idle: 500
          # 连接池中的最小空闲连接，默认值也是0。
          min-idle: 50
          # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
          max-active: 1000
          # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
          max-wait: 2000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.msdocsspringboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl